# 停车时间&金额修改重写规则
[rewrite_local]
^https://www\.hbbcck\.com/api/applet/queryPrice url script-response-body https://raw.githubusercontent.com/iYc227/iYcQX/main/parking_modify.js, tag=修改停车时间&免费停车, enabled=true

[mitm]
hostname = www.hbbcck.com
